name: iddsi_app
description: "IDDSI APP FOR THIRD YEAR 2025 BENG ELECTRICAL AND ELECTRONIC ENGINEERING"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  http: ^1.1.0
  email_validator: ^3.0.0
  lottie: ^3.3.2
  timeago: ^3.4.0

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_auth_web: ^6.0.4
  shared_preferences: ^2.3.0
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  cloud_functions: ^6.0.3

  js: ^0.7.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  flutter_tts: ^4.2.3
  speech_to_text: ^7.0.0
  
  # Audio and media packages
  record: ^5.1.2
  path_provider: ^2.1.4
  audioplayers: ^6.0.0
  firebase_storage: ^13.0.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

# Fix for record_linux compatibility issue and web package compatibility
dependency_overrides:
  record: 5.1.2
  record_platform_interface: 1.2.0
  web: ^1.0.0
  firebase_core_platform_interface: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/iddsi-logo.png
    - assets/food/
    - assets/speech.logo.png
    - assets/background.png
    - assets/menu_icon.svg
    - assets/x_icon.svg
    - assets/arrow_icon.svg
    - assets/info_icon.svg
    - assets/dysphagia_icon.svg
    - assets/symptoms_icon.svg
    - assets/disclaimer_icon.svg
    - assets/images/background.png
    - assets/images/chat.png
    - assets/images/kid.png
    - assets/images/oldman.png
    - assets/food/custard.png
    - assets/food/liquidised_shicken_soup.png
    - assets/food/mageu.png
    - assets/food/pureed_vegetable_curry.png
    - assets/food/smooth_maize_porride.png
    - assets/icons/Account.svg
    - assets/icons/arrow1.svg
    - assets/icons/framework_h.svg
    - assets/icons/framework.svg
    - assets/icons/home.svg
    - assets/icons/notification.svg
    - assets/icons/profile.svg
    - assets/icons/testing.svg
    - assets/icons/top_menu.svg
    - assets/images/background2.png
    - assets/images/logo_new.png
    - assets/images/dysphagia_care.png
    - assets/animations/angry.json
    - assets/animations/sad.json
    - assets/animations/neutral.json
    - assets/animations/happy.json
    - assets/animations/superMood.json
    - assets/
    - assets/images/
    - assets/food/
    - assets/icons/
    - assets/icons_sm/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/dysphagia_care2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/dysphagia_care2.png"
